### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/media/data2/ZSLdata/VGSE/AWA2/word2vec_splits.mat'

### ISSUE THREAD

**Issue by sorrowyn** [wenjiaXu/VGSE#2]
```
FileNotFoundError: [Errno 2] No such file or directory: '/media/data2/ZSLdata/VGSE/AWA2/word2vec_splits.mat'
FileNotFoundError: [Errno 2] No such file or directory: '/media/data2/ZSLdata/VGSE/AWA2/VGSE_SMO_splits.mat'
```
How to get these crucial files.
![图片](https://user-images.githubusercontent.com/19569162/177043717-d16d9b46-6e50-498e-8282-9eae5655c555.png)

**Comment by wenjiaXu** [comment]
Hi, the data is updated. You can find it here: https://drive.google.com/file/d/16PYq75orhr0UoE1OejjMfhullkr5ZZ9N/view?usp=sharing

**Comment by sorrowyn** [comment]
> Hi, the data is updated. You can find it here: https://drive.google.com/file/d/16PYq75orhr0UoE1OejjMfhullkr5ZZ9N/view?usp=sharing

Thank you for your timely help!
